[package]
name = "pyre"
version = "0.1.1"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "pyre"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "^0.13.0"
features = ["extension-module"]

[dependencies]
http = "0.2"
httparse = "1.3.4"
httpdate = "0.3"

bytes = "1.0.1"
rustc-hash = "1.1.0"
crossbeam = "0.8.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version="^0.3.2", features = ["disable_initial_exec_tls", "background_threads"] }

[profile.release]
lto = "fat"
codegen-units = 1
